/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  transpilePackages: [
    '@vault/mod-recipe-sharing',
    '@vault/mod-diy-skill-sharing',
    '@vault/mod-creative-collaboration-hub',
    '@vault/mod-branching-storytelling',
    '@vault/mod-influencer-campaign-manager',
    '@vault/mod-affiliate-dashboard',
    '@vault/mod-content-calendar-approval',
    '@vault/mod-portfolio-case-study-builder',
    '@vault/mod-course-completion-tracker',
    '@vault/mod-community-membership-portal',
    '@vault/mod-digital-product-storefront',
    '@vault/mod-newsletter-monetization',
    '@vault/mod-hyperlocal-skill-exchange',
    '@vault/mod-sustainable-goods-repair',
    '@vault/mod-tutor-search',
    '@vault/mod-remote-job-board',
    '@vault/mod-mentor-marketplace',
    '@vault/mod-pet-service-locator',
    '@vault/mod-event-venue-finder',
    '@vault/mod-specialty-product-aggregator',
    '@vault/mod-local-service-comparison',
    '@vault/mod-freelancer-directory',
    '@vault/mod-restaurant-reservation',
    '@vault/mod-online-booking-scheduling',
    '@vault/mod-subscription-box-management',
    '@vault/mod-referral-tracking',
    '@vault/mod-staff-scheduling',
    '@vault/mod-review-collection',
    '@vault/mod-service-agreement-generator',
    '@vault/mod-client-progress-tracker',
    '@vault/mod-quote-invoice-builder',
    '@vault/mod-appointment-booking',
    '@vault/mod-task-scheduling-motivation',
    '@vault/mod-digital-decluttering',
    '@vault/mod-form-builder',
    '@vault/mod-personal-dashboard',
    '@vault/mod-recurring-task-manager',
    '@vault/mod-employee-onboarding-checklist',
    '@vault/mod-proposal-generator',
    '@vault/mod-contract-status-tracker',
    '@vault/mod-internal-knowledge-base',
    '@vault/mod-custom-client-portal',
    '@vault/mod-flashcard-spaced-repetition',
    '@vault/mod-habit-tracker',
    '@vault/mod-minimalist-timer',
    '@vault/mod-quick-note-taker','@vault/mod-unit-converter'],
};
export default nextConfig;
